sudo: required

services:
  - docker

# 'bash' is not a travis language. See https://docs.travis-ci.com/user/languages/
# language: generic
language: bash

# See also:
# 1. https://github.com/justincormack/cross-docker
# 2. https://docs.docker.com/docker-for-mac/multi-arch/
# 3. https://github.com/docker-library/official-images#architectures-other-than-amd64
# 4. https://github.com/docker-library/official-images/blob/a7ad3081aa5f51584653073424217e461b72670a/bashbrew/go/vendor/src/github.com/docker-library/go-dockerlibrary/architecture/oci-platform.go#L14-L25
#  "amd64":   {OS: "linux", Architecture: "amd64"},
#  "arm32v5": {OS: "linux", Architecture: "arm", Variant: "v5"},
#  "arm32v6": {OS: "linux", Architecture: "arm", Variant: "v6"},
#  "arm32v7": {OS: "linux", Architecture: "arm", Variant: "v7"},
#  "arm64v8": {OS: "linux", Architecture: "arm64", Variant: "v8"},
#  "i386":    {OS: "linux", Architecture: "386"},
#  "ppc64le": {OS: "linux", Architecture: "ppc64le"},
#  "s390x": {OS: "linux", Architecture: "s390x"},
#  "windows-amd64": {OS: "windows", Architecture: "amd64"},


# matrix:
#     include:
#         - os: linux
#           env: MY_ARCH=arm32v6
#         - os: linux
#           env: MY_ARCH=arm32v7
#         - os: osx
#           env: MY_ARCH=arm64v8

env:
  global:
    - IMAGE_NAME=biarms/test-build

# From https://docs.travis-ci.com/user/customizing-the-build/
# install: true

before_install:
  - echo "before_install"

script:
  - VERSION=$(grep "ENV VERSION" Dockerfile | sed 's/.*=//')
  - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
  - >
    if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      echo "We are building the master branch: version is official version."
      export IMAGE_VERSION="${VERSION}"
    else
      echo "We are not building the master branch. Building a beta version then"
      export IMAGE_VERSION="${VERSION}-beta-${BUILD_NUMBER}"
    fi
  - echo "MY_ARCH=${MY_ARCH} - IMAGE_VERSION=${IMAGE_VERSION} - TRAVIS_BRANCH=${TRAVIS_BRANCH} - DOCKER_USERNAME=${DOCKER_USERNAME}"
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker version
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # get qemu-arm-static binary
  - mkdir tmp
  - pushd tmp
  - curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.9.1-1/x86_64_qemu-arm-static.tar.gz
  - tar xzf qemu-arm-static.tar.gz
  - pwd && ls -lrta # debug
  - popd
  # When https://github.com/docker/cli/pull/138 merged branch will be part of an official release:
  # docker manifest create biarms/mysql biarms/mysql-arm
  # docker manifest annotate biarms/mysql biarms/mysql-arm --os linux --arch arm
  # docker manifest push new-list-ref-name
  #
  # In the mean time, we use: https://github.com/estesp/manifest-tool
  # https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-arm64 &&
  - curl -L -o manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-386
  - chmod +x manifest-tool
  - ls -l manifest-tool
  - bash -c './manifest-tool --version'
  - >
    echo "image: ${IMAGE_NAME}:${IMAGE_VERSION}" > manifest.yaml
  - >
    echo "manifests:" >> manifest.yaml
  - >
    echo "  - image: ${IMAGE_NAME}:linux-arm-${IMAGE_VERSION} " >> manifest.yaml
  - >
    echo "    platform: " >> manifest.yaml
  - >
    echo "      architecture: arm " >> manifest.yaml
  - >
    echo "      os: linux " >> manifest.yaml
  - >
    echo "   #TODO: armv6l, armv7l, aarch64" >> manifest.yaml
  - cat manifest.yaml
  - BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - VCS_REF=$(git rev-parse --short HEAD)
  - pwd && docker build --build-arg VCS_REF=$VCS_REF --build-arg BUILD_DATE=${BUILD_DATE} -t ${IMAGE_NAME}:build .

after_success:
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker tag ${IMAGE_NAME}:build ${IMAGE_NAME}:linux-arm-${IMAGE_VERSION}
  - docker push ${IMAGE_NAME}:linux-arm-${IMAGE_VERSION}
  - bash -c './manifest-tool push from-spec manifest.yaml'
  # TODO: if [[ "${TRAVIS_BRANCH}" == "master" ]] is certainly not enough: the 'Pull request build is a 'master' build -> images are pushed on dockerhub even if the pull request is not accepted)
  - >
    if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      echo "Building master branch. Let's also push the 'latest' tag on docker hub"
      docker tag ${IMAGE_NAME}:build ${IMAGE_NAME}:latest
      docker push ${IMAGE_NAME}:latest
    fi
